<a href="https://colab.research.google.com/github/AePotato/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/Part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra For CHE

### Objectives
At the end of this activity you will be able to:
1. Be familiar with matrices and their relation to linear equations.
2. Perform basic matrix operations.
3. Program and translate matrix equations and operations using Python.

#Discussion

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

##Matrices

$$
A = \left\{
    \begin{array}\
        x + y \\ 
        4x - 10y
    \end{array}
\right. \\
B = \left\{
    \begin{array}\
        x+y+z \\ 
        3x -2y -z \\
        -x + 4y +2z
    \end{array}
\right. \\
c = \left\{
    \begin{array}\
      w-2x+3y -4z \\
      3w-x-2y+z  \\
      2w-x+3y-2z
    \end{array}
\right. \\
$$

:$$
A = \begin{bmatrix} 1 & 1 \\ 4 & -10\end{bmatrix} \\
B = \begin{bmatrix} 1 &  1& 1 \\ 3 & -2 & -1 \\ 1 & 3 & 5 \end{bmatrix} \\
C = \begin{bmatrix} 1 & 3 & 4 & -4 \\ 3 & 4 & -3 & 4 \\ 5 & 6 & 8 & 9 \end{bmatrix} \\
:$$

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$


##
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [3]:
##
def describe_mat(matrix):
  print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [6]:
##
A = np.array([
              [1, 2],
              [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [7]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [8]:
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)


Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [10]:
H = np.array([3,6,9,12])
describe_mat(H)

Matrix:
[ 3  6  9 12]

Shape:	(4,)
Rank:	1



#Categorizing Matrices

##Acording to shape

##Row & Column

In [11]:
## Declaring a Row Matrix

rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)


Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [13]:
## Declaring column Matrix

col_mat = np.array([
    [5],
    [10],
    [15]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[ 5]
 [10]
 [15]]

Shape:	(3, 1)
Rank:	2



###Square Matrices

In [14]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')


In [15]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)


Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##According to element values

###

In [16]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [17]:
null_mat = np.array([])
describe_mat(null_mat)

Matrix is Null


###Zero Matrix

In [18]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


###Diagonal Matrix

In [20]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [22]:
d = np.diag([2,3,5,7])
d

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 7]])

In [23]:
r = np.diag([3,6,9,5])
r

array([[3, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 9, 0],
       [0, 0, 0, 5]])

In [25]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###Upper Triangular Matrix

In [29]:
np.array([
          [1,2,3,4],
          [5,6,7,8],
          [8,9,10,11]
])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [30]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)


array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

In [31]:
np.tril(F)

array([[ 2,  0,  0,  0,  0],
       [ 2, -3,  0,  0,  0],
       [ 2, -3,  4,  0,  0],
       [ 2, -3,  4, -5,  0],
       [ 2, -3,  4, -5,  6]])

In [ ]:
np.array([
          
])

#Practice

###1. 