<a href="https://colab.research.google.com/github/AePotato/Linear-Algebra_ChE_2nd-Sem-2021-2022/blob/main/TrialNErrorLinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Task 1
Create a function named mat_desc()  that througouhly describes a matrix, it should:

  1. Displays the shape, size, and rank of the matrix.
  2. Displays whether the matrix is square or non-square.
  3. Displays whether the matrix is an empty matrix.
  4. Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

##Function Area

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_desc(matrix):
    if matrix.size > 0:
      is_square = True if matrix.shape[0] == matrix.shape[1] else False 
      print(f'Matrix:\n{matrix}\n\nDescription:\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nSquare: {is_square}\n')
    else:
      print('Matrix is empty')

##Matrix Declaration

In [ ]:
P = zero_mat_row = np.zeros((3,3))
S = zero_mat_sqw = np.zeros((3,4))
C = zero_mat_rct = np.zeros((4,3))
L = ones_mat_row = np.ones((3,4))
D = ones_mat_sqr = np.ones((4,3))
U = ones_mat_rct = np.ones((4,4))

In [ ]:
M = np.array([
              [33,44,49],
              [55,44,32],
              [23,18,20],
              [10,20,30]
])

In [ ]:
A = np.array([
              [10,20,30,40],
              [5,10,15,20],
              [60,50,33,78],
              [66,44,33,44],
              [66,11,22,88]
])

In [ ]:
R = np.array([])

##Test Area

In [ ]:
mat_desc(M)

Matrix:
[[33 44 49]
 [55 44 32]
 [23 18 20]
 [10 20 30]]

Description:

Shape:	(4, 3)
Rank:	2
Is Square: False



In [ ]:
mat_desc(A)

Matrix:
[[10 20 30 40]
 [ 5 10 15 20]
 [60 50 33 78]
 [66 44 33 44]
 [66 11 22 88]]

Description:

Shape:	(5, 4)
Rank:	2
Is Square: False



In [ ]:
mat_desc(R)

Matrix is empty


In [ ]:
mat_desc(P)

Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Description:

Shape:	(3, 3)
Rank:	2
Is Square: True



In [ ]:
mat_desc(U)

Matrix:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Description:

Shape:	(4, 4)
Rank:	2
Is Square: True



#Act 2

### Task 2
Create a function named mat_operations() that takes in two matrices a input parameters it should:

  1. Determines if the matrices are viable for operation and returns your own error message if they are not viable.
  2. Returns the sum of the matrices.
  3. Returns the difference of the matrices.
  4. Returns the element-wise multiplication of the matrices.
  5. Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than (3,3) . In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la
%matplotlib inline

In [ ]:
def mat_operation(sum):
  print('Sum: ')
def mat_operation(dif):
  print('Difference: ')
def mat_operation(div):
  print('Quotient: ')
def mat_operation(mul):
  print('Product is: ')

In [ ]:
E = np.array([
              [10,20,30,11],
              [12,-13,-15,14],
              [23,-1,3,7],
              [5,-9,9,7]
])
G = np.array([
              [1,2,3,10],
              [12,-2,15,4],
              [2,1,0,6],
              [5,0,18,-7]
])
N = np.array([
              [0,79,40,-1],
              [12,-8,-15,14],
              [0,1,-3,7]
])

In [ ]:
while True:
        try:
            print(r)
        except ValueError:
            print(" operands could not be broadcast together with shapes (4,4) (3,4).")

NameError: ignored

In [ ]:
r = E+N
r

ValueError: ignored